module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/EekDsKzbgyfACsN1uO0Ehe?mode=gi_t',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/d6afvt.jpg',
    NEWSLETTER_JID: '120363427671810776@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: '𝐀𝐔𝐑𝐀-𝐌𝐈𝐍𝐈 ',
    OWNER_NAME: 'Gagana anuhas',
    OWNER_NUMBER: '94713047504,94701138566',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> 𝐀𝐔𝐑𝐀-𝐌𝐈𝐍𝐈 Ｖ1',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029Vb7nfOX3bbUwsPm6Oe0w',
};
